#!/usr/bin/env bash

#VARIABLES
NAME="sample"
SOURCE="$PWD/../INPUT/"
TO=$PWD
TEMPLATE=${PWD}"/template"

#echo "
cd ${SOURCE}
for i in stech_*; do
    dirr="${TO}/$i"
    mkdir $dirr
    cd $i
    licz=0; iter=0;
    for j in *.xyz; do
	div=$((iter % 2))
	if [ $div -eq 0 ] && [ $licz -lt 50 ]; then
	    mkdir $dirr/${NAME}$licz
	    cp $j $dirr/${NAME}$licz/start.in
	    ((licz++))
	fi
	((iter++))
    done
    echo $i $iter $licz
    cd ${SOURCE}
done
#" > tmp; rm tmp

cd $TO
for i in stech*; do
    rm -r $i/template
    cp -r ${TEMPLATE} $i
    cp -r skrypty do_for run $i
    cd $i; ./do_for "g" ; cd ..;
done

