#!/bin/bash 
#PBS -N widom
#PBS -l nodes=1:ppn=1,mem=512mb
#PBS -l walltime=03:00:00
#PBS -q long
#PBS -e error_log


echo 'PBS nodes:'
cat $PBS_NODEFILE > $PBS_O_WORKDIR/started_qsub

cd $PBS_O_WORKDIR

#cp $PBS_O_WORKDIR/* $TMPDIR
#cd $TMPDIR

echo $PBS_JOBID > jobid
time env OMP_NUM_THREADS=1 OMP_SCHEDULE="static" ./mcdif_04122015 conf.in

#mv $TMPDIR/* $PBS_O_WORKDIR

