#!/bin/bash

ID=`hostname`
pth=$PWD
SRC="$pth"

SOURCE="$PWD/../MI/"
TO=$PWD

cp $SOURCE/total.dat $TO

#rm -r $SRC
#mkdir $SRC

cp ${SRC}/all.dat $SRC/${ID}.all
cp ${SRC}/results.dat $SRC/${ID}.mi
cp ${SRC}/total.dat $SRC/${ID}.total

#cp ${pth}/results/R2/static.factor.dat $SRC/${ID}_static_f.r2
#cp ${pth}/results/R2/static.factors.dat $SRC/${ID}_static.r2
#cp ${pth}/results/R2/tf.point $SRC/${ID}_tf.point
#cp ${pth}/results/R2/tf.points $SRC/${ID}_tf.points
#cp ${pth}/results/R2/avgdR2.dat $SRC/${ID}_avgdR2.dat
#cp ${pth}/results/R2/bin/std.dat $SRC/${ID}_std.dat

#cp ${pth}/results/R/static.factor.dat $SRC/${ID}_static_f.r
#cp ${pth}/results/R/static.factors.dat $SRC/${ID}_static.r
#cp ${pth}/results/R/cf.point $SRC/${ID}_cf.point
#cp ${pth}/results/R/cf.points $SRC/${ID}_cf.points
#cp ${pth}/results/R/avgdR.dat $SRC/${ID}_avgdR.dat
