#!/bin/bash 
echo "Zaczynam fitowac..."

export LC_ALL=C

#module load python/2.7.8
#module add libs/python

module add libs/python-numpy
module add libs/python-scipy

start_path=$PWD
script_path=$start_path/scripts

cd data
rm results.dat all.dat
for kat in ./S*; do
    stech=${kat##./S}
    cd $kat
    cp ${script_path}/* .
    for i in stech.dat; do
    awk -v NUMBER=$stech '{s=$3*100; s=int(s+0.5);s=s/100;if(s == NUMBER) print >> "tmp.dat" }' $i
    mv tmp.dat path.dat
    done
    ./cal_avg.py path.dat
    cat sr.dat >> ../results.dat
    cat path.dat >> ../all.dat
    cd ..
done

sort -n -k 1,1 results.dat > tmp.dat
cat tmp.dat > results.dat
rm tmp.dat
cd ..
cp ./data/results.dat .
cp ./data/all.dat .




