#! /usr/bin/env bash

chem1=`awk '{print $1}' chem.in`
chem2=`awk '{print $2}' chem.in`
file1=`ls u*N.dat`

out=$PWD
num=`awk 'END{print int(NR/2)}' $file1`

echo $file1 $num

outT=1400.0
outS=${out##*/S}
./cal_F.py $file1 $num $outT $outS
cat srF.dat >> ../../F.dat




